# Generated by Django 4.1.1 on 2022-10-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choice_text_answer_answer_text_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'otwarte'), (2, 'zamknięte')], default=1),
        ),
    ]
